#!/usr/bin/env node
/*
 * patch-matrix.js — let the owner's matrix fill itself in from real runs.
 *
 * docs/TEST-MATRIX.md is the scenario catalog and its cells are hand-written
 * prose carrying citations, field notes and dates. That prose is the valuable
 * part and this script does not touch it.
 *
 * What it DOES do is maintain one clearly-fenced block near the top of the
 * document — "last automated run" — listing every scenario the bench decided
 * and what it decided. Rewriting the human cells would be the wrong trade:
 * a bench verdict is one night on two phones on a bench, and the matrix cell
 * is the accumulated field record. The block sits beside the table so a reader
 * can see both, and it is rewritten in place on every patch so it can never
 * drift into a stale second opinion.
 *
 *   node patch-matrix.js <scorecard.json> <docs/TEST-MATRIX.md>
 */

'use strict';

const fs = require('fs');

const [, , scorePath, matrixPath] = process.argv;
if (!scorePath || !matrixPath) {
  process.stderr.write('usage: patch-matrix.js <scorecard.json> <TEST-MATRIX.md>\n');
  process.exit(2);
}

const doc = JSON.parse(fs.readFileSync(scorePath, 'utf8'));
const md = fs.readFileSync(matrixPath, 'utf8');

const BEGIN = '<!-- p2p-bench:begin -->';
const END = '<!-- p2p-bench:end -->';

const devices = [
  doc.devices.a1 !== 'none' ? `A1 ${doc.devices.a1}` : null,
  doc.devices.a2 !== 'none' ? `A2 ${doc.devices.a2}` : null,
  doc.devices.iphone !== 'none' ? `iPhone ${doc.devices.iphone}` : null,
].filter(Boolean).join(' · ') || 'no devices';

const t = doc.totals;

const rows = doc.scenarios
  .map((s) => {
    const cf = s.verdict === 'MANUAL' ? '—' : s.counterfactual;
    return `| ${s.verdict} | TIER-${s.tier} | \`${s.id}\` | ${s.title} | ${cf} |`;
  })
  .join('\n');

const block = `${BEGIN}
### Last automated run — \`tools/p2p-bench\`

**${doc.stamp}** · tree \`${(doc.tree || '').slice(0, 7)}\` · ${devices}
**${t.pass} pass · ${t.fail} fail · ${t.skip} skipped · ${t.manual} manual** — ${t.automated_share}% of the catalog was machine-decidable on the devices cabled for this run.

This block is regenerated by \`tools/p2p-bench/bench.sh --patch-matrix\` and is
the BENCH's opinion only: one night, on the phones listed above, reading
logcat, \`dumpsys audio\` and the accessibility tree. The prose cells in the
tables below are the accumulated FIELD record and are never overwritten by
this tool. Where the two disagree, the field record is the older and usually
the wiser witness — and the disagreement is the interesting part.

Every row names the thing the phones say when the feature is broken. A row
whose counterfactual column reads "—" is a TIER-MANUAL row: it is listed so
the catalog is complete, and it is never given an automated verdict.

| Verdict | Tier | Scenario | What it drives | What a break looks like |
|---|---|---|---|---|
${rows}
${END}`;

let out;
if (md.includes(BEGIN) && md.includes(END)) {
  out = md.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}`), () => block);
} else {
  // First patch: land the block after the document's opening prose, before
  // the first table's heading, so it reads as a status banner rather than an
  // appendix nobody scrolls to.
  const anchor = md.indexOf('\n## ');
  if (anchor === -1) {
    out = `${md.trimEnd()}\n\n${block}\n`;
  } else {
    out = `${md.slice(0, anchor)}\n\n${block}\n${md.slice(anchor)}`;
  }
}

fs.writeFileSync(matrixPath, out);
process.stdout.write(`patched ${matrixPath} — ${doc.scenarios.length} scenarios from run ${doc.stamp}\n`);
