/**
 * Content assertions for the BUNDLED brc-events-2026 pack. The pack must be
 * the REAL 2026 Playa Events listing (playaevents.burningman.org via
 * tools/fetch_playaevents.py + load_events.py), never the scaffold-era
 * invented placeholder — with the placeholder enabled, event-shaped
 * questions were answered from fictional cards ("Morning Coffee & Consent
 * Talk"), the last untruthful content in the app.
 *
 * These mirror the load_events.py build gates (--expect-min /
 * --expect-dates / --forbid-title) so a regression is caught on every
 * `npm test` even if the pack is regenerated by hand.
 */

interface EventRow {
  title: string;
  desc: string;
  day: string;
  date: string;
  time_start: string;
  time_end: string;
  camp: string;
  location: string;
}

const events = require('../assets/packs/brc-events-2026/events.json') as EventRow[];
const manifest = require('../assets/packs/brc-events-2026/pack.json') as {
  id: string;
  version: number;
  description: string;
};

// Fictional titles/camps invented for the scaffold placeholder. None of
// these exact strings may appear in real data under the same meaning; the
// title list is specific enough that any hit means the placeholder leaked.
const PLACEHOLDER_TITLES = [
  'Morning Coffee & Consent Talk',
  'Dawn Patrol at the Trash Fence',
  'Power Yoga at Eight',
];
const PLACEHOLDER_CAMPS = ['Camp Bendy Hippo', 'Flapjack Cartel', 'Sparks & Recreation'];

describe('bundled brc-events-2026 pack content', () => {
  test('is real-sized: at least 500 events (placeholder had 30)', () => {
    expect(events.length).toBeGreaterThanOrEqual(500);
  });

  test('contains no invented placeholder events or camps', () => {
    const titles = new Set(events.map(e => e.title));
    const camps = new Set(events.map(e => e.camp));
    for (const t of PLACEHOLDER_TITLES) {
      expect(titles.has(t)).toBe(false);
    }
    for (const c of PLACEHOLDER_CAMPS) {
      expect(camps.has(c)).toBe(false);
    }
  });

  test('every date is inside the 2026 event window (Aug 30 - Sep 8, Exodus day)', () => {
    // Sep 8 is Exodus support's last day (11:59 pm Tuesday) — the "Exodus
    // support ends" milestone is the one row that lands there.
    for (const e of events) {
      expect(e.date >= '2026-08-30' && e.date <= '2026-09-08').toBe(true);
    }
  });

  test('carries the city milestones the listing never publishes', () => {
    const titles = new Set(events.filter(e => e.camp === 'Black Rock City').map(e => e.title));
    for (const t of ['Gate opens', 'Man Burn', 'Temple Burn', 'Box Office closes',
                     'Event officially ends', 'Exodus support ends']) {
      expect(titles.has(t)).toBe(true);
    }
    const man = events.find(e => e.title === 'Man Burn')!;
    expect(man.date).toBe('2026-09-05');
    expect(man.day).toBe('Saturday');
    const temple = events.find(e => e.title === 'Temple Burn')!;
    expect(temple.date).toBe('2026-09-06');
    // Exact burn times are unpublished for 2026 (corpus rule): the rows must
    // not invent one. Blank time_start is legal — untimed events survive the
    // day-window filter and simply carry no clock on the card.
    expect(man.time_start).toBe('');
    expect(temple.time_start).toBe('');
  });

  test('rows are app-schema valid (installer would reject otherwise)', () => {
    for (const e of events) {
      expect(e.title.length).toBeGreaterThan(0);
      expect(e.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      if (e.time_start !== '') {
        expect(e.time_start).toMatch(/^\d{2}:\d{2}$/);
      }
      if (e.time_end !== '') {
        expect(e.time_end).toMatch(/^\d{2}:\d{2}$/);
      }
    }
  });

  test('pack version was bumped for the real-data swap (devices reinstall)', () => {
    expect(manifest.id).toBe('brc-events-2026');
    expect(manifest.version).toBeGreaterThanOrEqual(2);
    expect(manifest.description).not.toMatch(/invented placeholder/i);
  });

  test('searchable breadth: real listing spans many camps and both weekend days', () => {
    const camps = new Set(events.map(e => e.camp).filter(c => c.length > 0));
    expect(camps.size).toBeGreaterThanOrEqual(200);
    const dates = new Set(events.map(e => e.date));
    expect(dates.has('2026-08-30')).toBe(true); // gate-open Sunday
    expect(dates.size).toBeGreaterThanOrEqual(7);
  });
});
