/**
 * THE IN-APP SCANNER, end to end (owner, 2026-08-25: "should be a link/icon
 * to open camera app to scan qr codes, otherwise app has to be exited to
 * scan manually").
 *
 * Every QR in this app was a code to HOLD UP. Taking one meant leaving Playa
 * Pal for the camera app, tapping a notification, and finding the way back —
 * four steps in the dust with a person waiting. "Scan their code" takes one
 * photo and reads it here.
 *
 * WHAT THIS SUITE CAN AND CANNOT PROVE. It runs the SHIPPED decode path over
 * a real JPEG of a real code: the QR is generated by `qrcode`, which is the
 * engine `react-native-qrcode-svg` renders the app's codes with, so the bits
 * under test are the bits a camper photographs. What it cannot prove is
 * optics — focus, dust, glare, a phone held at an angle — or how long the
 * pure-JS decode takes under Hermes. Those are the device's to answer.
 *
 * Three kinds of test, deliberately separated (the podLinkWiring.test.ts
 * shape):
 *   - the decode path over synthesised frames and JPEGs, with negative
 *     controls, because a scanner that says yes to everything looks like a
 *     working scanner;
 *   - the delivery seam — one URL handler, whoever found the URL;
 *   - SOURCE assertions that the surfaces are actually wired to it, each
 *     written to die on a specific mutation named beside it.
 */

let mockConn: any;
jest.mock('../src/events/db', () => ({
  getDb: () => mockConn,
  getSetting: () => null,
  setSetting: () => {},
}));

import {
  base64ToBytes,
  decodeQrFromFrame,
  decodeQrFromJpegBase64,
  fitToScanBudget,
  MAX_SCAN_PIXELS,
  type Frame,
} from '../src/links/qrPhoto';
import {
  deliverIncomingUrl,
  isPlayaPalLink,
  subscribeIncomingUrl,
} from '../src/links/incoming';
import { ADDITIVE_COLUMNS, BASE_TABLES_SQL } from '../src/events/schema';
import {
  installFriendBundle,
  listFriends,
  type FriendCard,
} from '../src/friends/friendCard';
import {
  decodeFriendLink,
  encodeFriendSchemeLink,
} from '../src/friends/friendLink';
import { encodePodSchemeLink } from '../src/crews/podLink';

const { DatabaseSync } = require('node:sqlite');
// This RN-only repo ships no node type definitions, so Buffer arrives by
// require rather than as a global — the shape artPhoto.test.ts already uses.
const NodeBuffer = require('buffer').Buffer;
// The app's OWN QR engine: react-native-qrcode-svg renders through `qrcode`,
// so a code drawn here is the code a camper is looking at.
const QR = require('qrcode');
const jpeg = require('jpeg-js');

const CARD: FriendCard = {
  id: 'facec0de',
  seq: 3,
  name: 'Sparkle',
  camp: 'Camp Questionable',
  address: '4:30 & Esplanade',
  note: 'shade all afternoon, bar opens at sunset',
  updated_at: '2026-08-24T10:00:00.000Z',
  scope: 'crew',
};

const cardBundle = (card: FriendCard = CARD): string =>
  JSON.stringify({ kind: 'playapal-friend-card', format: 1, cards: [card] });

/** One phone's db, on the shipped DDL including the boot migrations. */
function makePhone(): void {
  const db = new DatabaseSync(':memory:');
  for (const sql of BASE_TABLES_SQL) {
    db.exec(sql);
  }
  for (const m of ADDITIVE_COLUMNS) {
    const cols = (db.prepare(`PRAGMA table_info(${m.table})`).all() as any[]).map(
      (c: any) => String(c.name),
    );
    if (!cols.includes(m.column)) {
      db.exec(m.ddl);
    }
  }
  mockConn = {
    execute(sql: string, params: unknown[] = []) {
      const stmt = db.prepare(sql);
      if (/^\s*(select|with|pragma)/i.test(sql)) {
        const rows = stmt.all(...(params as never[]));
        return {
          rows: { _array: rows, length: rows.length, item: (i: number) => rows[i] },
        };
      }
      stmt.run(...(params as never[]));
      return { rows: undefined };
    },
  };
}

/**
 * A code, drawn. `scale` is pixels per module and `quiet` the margin in
 * modules — the quiet zone is not decoration, it is what lets a finder
 * pattern be found, so a frame without one is a legitimate failure case.
 */
function drawQr(text: string, scale = 6, quiet = 4): Frame {
  const qr = QR.create(text, { errorCorrectionLevel: 'M' });
  const size = qr.modules.size;
  const side = (size + quiet * 2) * scale;
  const data = new Uint8ClampedArray(side * side * 4).fill(255);
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) {
      if (!qr.modules.get(r, c)) {
        continue;
      }
      for (let y = 0; y < scale; y += 1) {
        for (let x = 0; x < scale; x += 1) {
          const px = ((r + quiet) * scale + y) * side + (c + quiet) * scale + x;
          data[px * 4] = 0;
          data[px * 4 + 1] = 0;
          data[px * 4 + 2] = 0;
        }
      }
    }
  }
  return { data, width: side, height: side };
}

/** The frame as a camera JPEG, base64 — exactly what image-picker returns. */
function asPhotoB64(frame: Frame, quality = 80): string {
  const encoded = jpeg.encode(
    {
      data: NodeBuffer.from(
        frame.data.buffer,
        frame.data.byteOffset,
        frame.data.length,
      ),
      width: frame.width,
      height: frame.height,
    },
    quality,
  );
  return NodeBuffer.from(encoded.data).toString('base64');
}

/** The left `keep` fraction of a frame — a shot that cut the code in half. */
function cropWidth(frame: Frame, keep: number): Frame {
  const w = Math.floor(frame.width * keep);
  const data = new Uint8ClampedArray(w * frame.height * 4);
  for (let y = 0; y < frame.height; y += 1) {
    data.set(
      frame.data.subarray(y * frame.width * 4, (y * frame.width + w) * 4),
      y * w * 4,
    );
  }
  return { data, width: w, height: frame.height };
}

/** A frame with no code in it at all — a photo of a dusty table. */
function noiseFrame(width: number, height: number): Frame {
  const data = new Uint8ClampedArray(width * height * 4).fill(255);
  for (let i = 0; i < data.length; i += 4) {
    // Deterministic, so a failure here is reproducible rather than a mood.
    const v = (i * 2654435761) % 256;
    data[i] = v;
    data[i + 1] = (v + 40) % 256;
    data[i + 2] = (v + 90) % 256;
  }
  return { data, width, height };
}

beforeEach(() => {
  makePhone();
});

describe('reading a code out of a picture', () => {
  test('a drawn card code round-trips through the RAW frame', () => {
    const link = encodeFriendSchemeLink(cardBundle());
    expect(decodeQrFromFrame(drawQr(link))).toBe(link);
  });

  test('...and through a CAMERA JPEG, which is what actually arrives', () => {
    // The shipped function, over lossy bytes. JPEG ringing around the module
    // edges is the whole reason this is not the same test as the one above.
    const link = encodeFriendSchemeLink(cardBundle());
    const decoded = decodeQrFromJpegBase64(asPhotoB64(drawQr(link)));
    expect(decoded).toBe(link);
  });

  test('a pod invite code reads the same way — one scanner, three families', () => {
    const link = encodePodSchemeLink({ code: '4821', name: 'Dust Bunnies' });
    expect(decodeQrFromJpegBase64(asPhotoB64(drawQr(link)))).toBe(link);
  });

  test('NEGATIVE CONTROL: a picture with no code in it reads as no code', () => {
    // Without this the suite above proves nothing — a decoder that returned
    // the same string for every input would pass every test up to here.
    expect(decodeQrFromJpegBase64(asPhotoB64(noiseFrame(320, 240)))).toBeNull();
  });

  test('NEGATIVE CONTROL: bytes that are not a JPEG never throw', () => {
    // This runs with a camper watching; a malformed frame is an "aw, try
    // again", never a crash.
    expect(decodeQrFromJpegBase64('bm90IGEgamluZWc')).toBeNull();
    expect(decodeQrFromJpegBase64('')).toBeNull();
    expect(() => decodeQrFromJpegBase64('!!!!')).not.toThrow();
    expect(decodeQrFromJpegBase64('!!!!')).toBeNull();
  });

  test('a half-cropped code reads as NO code, never as a partial one', () => {
    // Why the failure copy talks about FRAMING. A shot that cuts the code in
    // half is the commonest bad scan, and the only safe answer is nothing:
    // a "best effort" read of a mangled payload would install a corrupt
    // card or open a link nobody encoded. Mutation: copy blaming the code
    // instead of the aim.
    const link = encodeFriendSchemeLink(cardBundle());
    expect(decodeQrFromFrame(cropWidth(drawQr(link), 0.6))).toBeNull();
  });

  test('MARGIN, MEASURED: heavy JPEG compression still reads', () => {
    // Quality 20 is far below anything a camera produces, and the code
    // survives it — so a failed scan in the field is optics (focus, glare,
    // a phone at an angle), not the codec. That distinction is what the
    // failure copy is allowed to claim.
    const link = encodeFriendSchemeLink(cardBundle());
    expect(decodeQrFromJpegBase64(asPhotoB64(drawQr(link), 20))).toBe(link);
  });
});

describe('base64 in, bytes out', () => {
  test('both alphabets decode to the same bytes, padding and all', () => {
    // Standard base64 is what image-picker returns; url-safe is what a
    // pasted payload can be. One decoder, so neither becomes a platform bug.
    const std = base64ToBytes('+/8=');
    const url = base64ToBytes('-_8');
    expect(Array.from(std!)).toEqual([0xfb, 0xff]);
    expect(Array.from(url!)).toEqual([0xfb, 0xff]);
  });

  test('whitespace is ignored, a stray character is refused', () => {
    expect(Array.from(base64ToBytes('QUJD\n  ')!)).toEqual([65, 66, 67]);
    expect(base64ToBytes('QU$D')).toBeNull();
  });
});

describe('the pixel budget', () => {
  test('a frame inside the budget is handed through untouched', () => {
    const frame = drawQr('https://playapal.lol/f#abc');
    expect(fitToScanBudget(frame)).toBe(frame);
  });

  test('an oversized frame is sampled down AND still decodes', () => {
    // Mutation: no budget at all. maxWidth is a REQUEST to the picker, so a
    // representation that ignores it would put a 12 MP frame through a
    // pure-JS scan on a phone in the dark. Nearest-neighbour is chosen
    // because a QR module is many pixels wide — this proves it survives.
    const link = encodeFriendSchemeLink(cardBundle());
    const big = drawQr(link, 6);
    const budget = Math.floor((big.width * big.height) / 4);
    const small = fitToScanBudget(big, budget);
    expect(small.width * small.height).toBeLessThanOrEqual(budget);
    expect(decodeQrFromFrame(small)).toBe(link);
    expect(MAX_SCAN_PIXELS).toBeGreaterThan(1_000_000);
  });
});

describe('a scanned link goes to the ONE handler, and nowhere else', () => {
  test('a friend link reaches subscribers verbatim', () => {
    const link = encodeFriendSchemeLink(cardBundle());
    const heard: string[] = [];
    const off = subscribeIncomingUrl(u => heard.push(u));
    expect(deliverIncomingUrl(link)).toBe(true);
    off();
    expect(heard).toEqual([link]);
  });

  test('the scanner does not install anything itself', () => {
    // THE LOAD-BEARING ONE. The merge rules, the consent ask and every
    // sentence a camper reads live in App.tsx's handler. Mutation: a
    // scanner that calls installFriendBundle directly — a second importer
    // that drifts the day one of them is edited.
    const link = encodeFriendSchemeLink(cardBundle());
    deliverIncomingUrl(link); // nobody subscribed
    expect(listFriends(mockConn)).toEqual([]);
  });

  test('delivered to the handler, the card lands through the normal importer', () => {
    // The handler's friend branch, transcribed — the same two lines App.tsx
    // runs, pinned to it by the source assertions below.
    const off = subscribeIncomingUrl(url => {
      const json = decodeFriendLink(url);
      if (json) {
        installFriendBundle(mockConn, json);
      }
    });
    deliverIncomingUrl(encodeFriendSchemeLink(cardBundle()));
    off();
    const friends = listFriends(mockConn);
    expect(friends).toHaveLength(1);
    expect(friends[0].name).toBe('Sparkle');
    expect(friends[0].address).toBe('4:30 & Esplanade');
  });

  test('a code that is not ours is refused, and says so by returning false', () => {
    // A scan that silently does nothing, in front of a person waiting, is
    // indistinguishable from a broken phone — the dead-end the pod QR
    // already paid for. The false is what buys the camper a sentence.
    const heard: string[] = [];
    const off = subscribeIncomingUrl(u => heard.push(u));
    expect(deliverIncomingUrl('https://example.com/whatever')).toBe(false);
    expect(deliverIncomingUrl('WIFI:S=CampWifi;T=WPA;P=dust;;')).toBe(false);
    off();
    expect(heard).toEqual([]);
  });

  test('all three families are recognised, by the shipped decoders', () => {
    // Mutation: a fourth copy of the URL patterns inside the scanner, which
    // then recognises a link the handler cannot read (or the reverse).
    expect(isPlayaPalLink(encodeFriendSchemeLink(cardBundle()))).toBe(true);
    expect(isPlayaPalLink(encodePodSchemeLink({ code: '4821' }))).toBe(true);
    expect(isPlayaPalLink('https://playapal.lol/f#not-valid-base64!!')).toBe(false);
  });

  test('unsubscribing actually stops delivery', () => {
    let calls = 0;
    const off = subscribeIncomingUrl(() => {
      calls += 1;
    });
    off();
    deliverIncomingUrl(encodeFriendSchemeLink(cardBundle()));
    expect(calls).toBe(0);
  });
});

describe('the surfaces are wired to the scanner', () => {
  // Named readScanFile: these suites are SCRIPTS, so a top-level const is
  // global and the obvious names already belong to other files (TS2451,
  // which jest never shows).
  const readScanFile = (p: string): string =>
    require('fs').readFileSync(p, 'utf8') as string;
  const app = readScanFile('App.tsx');
  const crew = readScanFile('src/crews/CrewSection.tsx');
  const friends = readScanFile('src/screens/FriendsSection.tsx');

  test('App.tsx subscribes its URL handler to scanned links', () => {
    // Mutation: the delivery seam shipping with no subscriber — the exact
    // bug class exportsHaveCallers.test.ts exists for, and the one that made
    // a scanned pod QR open the app and sit there.
    expect(app).toContain('subscribeIncomingUrl(handle)');
    // ...with the SAME function Linking gets. Mutation: a second handler
    // beside it, which is a second importer wearing a different name.
    expect(app).toContain("Linking.addEventListener('url', ev => handle(ev.url))");
  });

  test('the subscription is torn down with the effect', () => {
    // Mutation: dropping offScan() from the cleanup. A remount would then
    // stack handlers and every scan would install twice and alert twice.
    expect(app).toContain('const offScan = subscribeIncomingUrl(handle);');
    expect(app).toContain('offScan();');
  });

  test('both QR surfaces offer the camera beside the code', () => {
    // The owner's actual sentence: a link or icon to scan, so the app does
    // not have to be exited. Mutation: shipping the decoder with no button.
    expect(crew).toContain('scanCodeAndDeliver');
    expect(friends).toContain('scanCodeAndDeliver');
    expect(crew).toContain('accessibilityLabel="Scan a code with the camera"');
    expect(friends).toContain(
      'accessibilityLabel="Scan a friend\'s code with the camera"',
    );
  });

  test('the swap row shows a QR and shares no raw JSON anywhere', () => {
    // THE OWNER'S BUG, as a source fact. exportMyCard returns the BUNDLE;
    // handing it to a share sheet is what previewed as "{" on iOS. The pod
    // section must reach the card only through cardShare.ts now.
    expect(crew).toContain('CardQr');
    expect(crew).toContain('myCardShareLink');
    expect(crew).not.toContain('exportMyCard');
  });

  test('one builder serves both card-share doors', () => {
    // Mutation: FriendsSection keeping its own encodeFriendLink(exportMyCard)
    // call. Two copies of one gesture is how one of them stayed broken for a
    // week.
    expect(friends).toContain('myCardShareLink(conn)');
    expect(friends).not.toContain('encodeFriendLink(exportMyCard(conn))');
  });
});
